package com.lailem.app.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "BLACKLIST_IDS".
 */
public class BlacklistIds {

    private Long id;
    private Long createTime;
    private String userId;
    private String blackUserId;

    public BlacklistIds() {
    }

    public BlacklistIds(Long id) {
        this.id = id;
    }

    public BlacklistIds(Long id, Long createTime, String userId, String blackUserId) {
        this.id = id;
        this.createTime = createTime;
        this.userId = userId;
        this.blackUserId = blackUserId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getBlackUserId() {
        return blackUserId;
    }

    public void setBlackUserId(String blackUserId) {
        this.blackUserId = blackUserId;
    }

}
