package com.lailem.app.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CONVERSATION".
 */
public class Conversation extends ConversationBase{

    private Long id;
    private Long createTime;
    private String userId;
    private String needSendNick;
    private String needSendHead;
    private String tId;
    private String cType;
    private String isTop;
    private Long topTime;
    private Long updateTime;
    private String isNoTip;
    private String tipMsg;
    private Integer noReadCount;
    private String status;
    private String conversationId;
    private String chatBg;

    public Conversation() {
    }

    public Conversation(Long id) {
        this.id = id;
    }

    public Conversation(Long id, Long createTime, String userId, String needSendNick, String needSendHead, String tId, String cType, String isTop, Long topTime, Long updateTime, String isNoTip, String tipMsg, Integer noReadCount, String status, String conversationId, String chatBg) {
        this.id = id;
        this.createTime = createTime;
        this.userId = userId;
        this.needSendNick = needSendNick;
        this.needSendHead = needSendHead;
        this.tId = tId;
        this.cType = cType;
        this.isTop = isTop;
        this.topTime = topTime;
        this.updateTime = updateTime;
        this.isNoTip = isNoTip;
        this.tipMsg = tipMsg;
        this.noReadCount = noReadCount;
        this.status = status;
        this.conversationId = conversationId;
        this.chatBg = chatBg;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getNeedSendNick() {
        return needSendNick;
    }

    public void setNeedSendNick(String needSendNick) {
        this.needSendNick = needSendNick;
    }

    public String getNeedSendHead() {
        return needSendHead;
    }

    public void setNeedSendHead(String needSendHead) {
        this.needSendHead = needSendHead;
    }

    public String getTId() {
        return tId;
    }

    public void setTId(String tId) {
        this.tId = tId;
    }

    public String getCType() {
        return cType;
    }

    public void setCType(String cType) {
        this.cType = cType;
    }

    public String getIsTop() {
        return isTop;
    }

    public void setIsTop(String isTop) {
        this.isTop = isTop;
    }

    public Long getTopTime() {
        return topTime;
    }

    public void setTopTime(Long topTime) {
        this.topTime = topTime;
    }

    public Long getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    public String getIsNoTip() {
        return isNoTip;
    }

    public void setIsNoTip(String isNoTip) {
        this.isNoTip = isNoTip;
    }

    public String getTipMsg() {
        return tipMsg;
    }

    public void setTipMsg(String tipMsg) {
        this.tipMsg = tipMsg;
    }

    public Integer getNoReadCount() {
        return noReadCount;
    }

    public void setNoReadCount(Integer noReadCount) {
        this.noReadCount = noReadCount;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getConversationId() {
        return conversationId;
    }

    public void setConversationId(String conversationId) {
        this.conversationId = conversationId;
    }

    public String getChatBg() {
        return chatBg;
    }

    public void setChatBg(String chatBg) {
        this.chatBg = chatBg;
    }

}
