package com.lailem.app.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "GROUPS".
 */
public class Group {

    private Long id;
    private Long createTime;
    private String groupId;
    private String groupType;
    private String name;
    private String squareSPic;
    private String sPic;
    private Long updateTime;
    private String intro;
    private String pic;
    private String groupNum;
    private Long startTime;
    private Long endTime;
    private String typeId;
    private String typeName;
    private String areaId;
    private String address;
    private String lon;
    private String lat;
    private Integer permission;

    public Group() {
    }

    public Group(Long id) {
        this.id = id;
    }

    public Group(Long id, Long createTime, String groupId, String groupType, String name, String squareSPic, String sPic, Long updateTime, String intro, String pic, String groupNum, Long startTime, Long endTime, String typeId, String typeName, String areaId, String address, String lon, String lat, Integer permission) {
        this.id = id;
        this.createTime = createTime;
        this.groupId = groupId;
        this.groupType = groupType;
        this.name = name;
        this.squareSPic = squareSPic;
        this.sPic = sPic;
        this.updateTime = updateTime;
        this.intro = intro;
        this.pic = pic;
        this.groupNum = groupNum;
        this.startTime = startTime;
        this.endTime = endTime;
        this.typeId = typeId;
        this.typeName = typeName;
        this.areaId = areaId;
        this.address = address;
        this.lon = lon;
        this.lat = lat;
        this.permission = permission;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    public String getGroupId() {
        return groupId;
    }

    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    public String getGroupType() {
        return groupType;
    }

    public void setGroupType(String groupType) {
        this.groupType = groupType;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSquareSPic() {
        return squareSPic;
    }

    public void setSquareSPic(String squareSPic) {
        this.squareSPic = squareSPic;
    }

    public String getSPic() {
        return sPic;
    }

    public void setSPic(String sPic) {
        this.sPic = sPic;
    }

    public Long getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    public String getIntro() {
        return intro;
    }

    public void setIntro(String intro) {
        this.intro = intro;
    }

    public String getPic() {
        return pic;
    }

    public void setPic(String pic) {
        this.pic = pic;
    }

    public String getGroupNum() {
        return groupNum;
    }

    public void setGroupNum(String groupNum) {
        this.groupNum = groupNum;
    }

    public Long getStartTime() {
        return startTime;
    }

    public void setStartTime(Long startTime) {
        this.startTime = startTime;
    }

    public Long getEndTime() {
        return endTime;
    }

    public void setEndTime(Long endTime) {
        this.endTime = endTime;
    }

    public String getTypeId() {
        return typeId;
    }

    public void setTypeId(String typeId) {
        this.typeId = typeId;
    }

    public String getTypeName() {
        return typeName;
    }

    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    public String getAreaId() {
        return areaId;
    }

    public void setAreaId(String areaId) {
        this.areaId = areaId;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getLon() {
        return lon;
    }

    public void setLon(String lon) {
        this.lon = lon;
    }

    public String getLat() {
        return lat;
    }

    public void setLat(String lat) {
        this.lat = lat;
    }

    public Integer getPermission() {
        return permission;
    }

    public void setPermission(Integer permission) {
        this.permission = permission;
    }

}
