package com.lailem.app.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "MESSAGE".
 */
public class Message extends MessageBase{

    private Long id;
    private Long createTime;
    private String userId;
    private String tId;
    private String fId;
    private String mType;
    private String sType;
    private String fHead;
    private String fNick;
    private String mId;
    private String status;
    private String conversationId;
    private String isRead;
    private String isReadOne;
    private Long sTime;
    private String msg;

    public Message() {
    }

    public Message(Long id) {
        this.id = id;
    }

    public Message(Long id, Long createTime, String userId, String tId, String fId, String mType, String sType, String fHead, String fNick, String mId, String status, String conversationId, String isRead, String isReadOne, Long sTime, String msg) {
        this.id = id;
        this.createTime = createTime;
        this.userId = userId;
        this.tId = tId;
        this.fId = fId;
        this.mType = mType;
        this.sType = sType;
        this.fHead = fHead;
        this.fNick = fNick;
        this.mId = mId;
        this.status = status;
        this.conversationId = conversationId;
        this.isRead = isRead;
        this.isReadOne = isReadOne;
        this.sTime = sTime;
        this.msg = msg;
        initMsgObj(msg, fId, sType);
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getTId() {
        return tId;
    }

    public void setTId(String tId) {
        this.tId = tId;
    }

    public String getFId() {
        return fId;
    }

    public void setFId(String fId) {
        this.fId = fId;
    }

    public String getMType() {
        return mType;
    }

    public void setMType(String mType) {
        this.mType = mType;
    }

    public String getSType() {
        return sType;
    }

    public void setSType(String sType) {
        this.sType = sType;
    }

    public String getFHead() {
        return fHead;
    }

    public void setFHead(String fHead) {
        this.fHead = fHead;
    }

    public String getFNick() {
        return fNick;
    }

    public void setFNick(String fNick) {
        this.fNick = fNick;
    }

    public String getMId() {
        return mId;
    }

    public void setMId(String mId) {
        this.mId = mId;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getConversationId() {
        return conversationId;
    }

    public void setConversationId(String conversationId) {
        this.conversationId = conversationId;
    }

    public String getIsRead() {
        return isRead;
    }

    public void setIsRead(String isRead) {
        this.isRead = isRead;
    }

    public String getIsReadOne() {
        return isReadOne;
    }

    public void setIsReadOne(String isReadOne) {
        this.isReadOne = isReadOne;
    }

    public Long getSTime() {
        return sTime;
    }

    public void setSTime(Long sTime) {
        this.sTime = sTime;
    }

    public String getMsg() {
        return msg;
    }

    public void setMsg(String msg) {
        this.msg = msg;
    }

	@Override
	public String toString() {
		return "Message [id=" + id + ", createTime=" + createTime + ", userId=" + userId + ", tId=" + tId + ", fId=" + fId + ", mType=" + mType + ", sType=" + sType + ", fHead=" + fHead + ", fNick="
				+ fNick + ", mId=" + mId + ", status=" + status + ", conversationId=" + conversationId + ", isRead=" + isRead + ", isReadOne=" + isReadOne + ", sTime=" + sTime + ", msg=" + msg + "]";
	}
    
    

}
