package com.lailem.app.dao;

import com.lailem.app.bean.Base;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "REGION".
 */
public class Region extends Base{

    private Long id;
    private Long createTime;
    private String rId;
    private String pId;
    private String name;
    private String rType;
    private String path;
    private String cCode;
    private String lCode;
    private String vCode;

    public Region() {
    }

    public Region(Long id) {
        this.id = id;
    }

    public Region(Long id, Long createTime, String rId, String pId, String name, String rType, String path, String cCode, String lCode, String vCode) {
        this.id = id;
        this.createTime = createTime;
        this.rId = rId;
        this.pId = pId;
        this.name = name;
        this.rType = rType;
        this.path = path;
        this.cCode = cCode;
        this.lCode = lCode;
        this.vCode = vCode;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    public String getRId() {
        return rId;
    }

    public void setRId(String rId) {
        this.rId = rId;
    }

    public String getPId() {
        return pId;
    }

    public void setPId(String pId) {
        this.pId = pId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getRType() {
        return rType;
    }

    public void setRType(String rType) {
        this.rType = rType;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public String getCCode() {
        return cCode;
    }

    public void setCCode(String cCode) {
        this.cCode = cCode;
    }

    public String getLCode() {
        return lCode;
    }

    public void setLCode(String lCode) {
        this.lCode = lCode;
    }

    public String getVCode() {
        return vCode;
    }

    public void setVCode(String vCode) {
        this.vCode = vCode;
    }

}
