package com.lailem.app.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SYS_PROPERTY".
 */
public class SysProperty {

    private Long id;
    private Long createTime;
    private String name;
    private String propValue;

    public SysProperty() {
    }

    public SysProperty(Long id) {
        this.id = id;
    }

    public SysProperty(Long id, Long createTime, String name, String propValue) {
        this.id = id;
        this.createTime = createTime;
        this.name = name;
        this.propValue = propValue;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPropValue() {
        return propValue;
    }

    public void setPropValue(String propValue) {
        this.propValue = propValue;
    }

}
