package com.lailem.app.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USER".
 */
public class User {

    private Long id;
    private Long createTime;
    private String userId;
    private String nickname;
    private String head;
    private Long updateTime;
    private String name;
    private String phone;
    private String personalizedSignature;
    private String countryCode;
    private String userType;
    private String email;
    private String headBig;
    private String liveAreaId;
    private String sex;
    private String birthday;

    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    public User(Long id, Long createTime, String userId, String nickname, String head, Long updateTime, String name, String phone, String personalizedSignature, String countryCode, String userType, String email, String headBig, String liveAreaId, String sex, String birthday) {
        this.id = id;
        this.createTime = createTime;
        this.userId = userId;
        this.nickname = nickname;
        this.head = head;
        this.updateTime = updateTime;
        this.name = name;
        this.phone = phone;
        this.personalizedSignature = personalizedSignature;
        this.countryCode = countryCode;
        this.userType = userType;
        this.email = email;
        this.headBig = headBig;
        this.liveAreaId = liveAreaId;
        this.sex = sex;
        this.birthday = birthday;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public String getHead() {
        return head;
    }

    public void setHead(String head) {
        this.head = head;
    }

    public Long getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getPersonalizedSignature() {
        return personalizedSignature;
    }

    public void setPersonalizedSignature(String personalizedSignature) {
        this.personalizedSignature = personalizedSignature;
    }

    public String getCountryCode() {
        return countryCode;
    }

    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }

    public String getUserType() {
        return userType;
    }

    public void setUserType(String userType) {
        this.userType = userType;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getHeadBig() {
        return headBig;
    }

    public void setHeadBig(String headBig) {
        this.headBig = headBig;
    }

    public String getLiveAreaId() {
        return liveAreaId;
    }

    public void setLiveAreaId(String liveAreaId) {
        this.liveAreaId = liveAreaId;
    }

    public String getSex() {
        return sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    public String getBirthday() {
        return birthday;
    }

    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

}
